#!/bin/bash    

#for branch in `git branch -r | grep -v HEAD`;do echo -e `git show --format="%ci %cr" $branch | head -n 1` \\t$branch; done | sort -r

#for ref in $(git for-each-ref --sort=-committerdate --format="%(refname)" refs/heads/ refs/remotes ); do git log -n1 $ref --pretty=format:"%Cgreen%cr%Creset %C(yellow)%d%Creset% %C(bold blue)<%an>%Creset%n" | cat ; done | awk '! a[$0]++'

for ref in $(git for-each-ref --sort=-committerdate --format="%(refname:short)" refs/remotes );
do
	git log -n1 $ref --pretty=format:"%Cgreen%cr%Creset | %C(yellow)%d%Creset% | %C(bold blue)%an%Creset%n" | 	
  		while IFS='|' read date message author
  		do
    		printf '%-20s %-35s %-90s\n' "$date" "$author" "$message"
  		done
done